### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Veknasty** [ajaxxxxxxx/Deutsches-Uberreich-Updated#2]
Not sure if I'm just retarded and don't know how to manually download mods, but the mod doesn't work from either the Skymods download or on Github. Whenever I get to the part where I elect Thalmann no events pop up no matter how long I wait. and the in game guide doesn't have anything there that is helpful. Tried to ask for help on the discord posted on the discussions page however the link was invalid.

**Comment by Veknasty** [comment]
Fixed it

**Comment by ajaxxxxxxx** [comment]
Sorry the link was invalid. Here's a new one incase you need more help or have suggestions in the future.

https://discord.gg/4tzj4xC5
